<?php
  /**
  *Setting up of a account - an example 
  *
  *Consists of the following variables, which you can assign suitably 
  *<ul>
  *<li>$db_host = 'localhost';</li>
  *<li>$db_name = 'fdcl';</li>
  *<li>$db_user = 'cameralifeuser';</li>
  *<li>$db_pass = 'password';</li>
  *<li>$db_prefix = '';</li>
  *</ul>
  *
  *@version 2.6.2
  *@author Will Entriken <cameralife@phor.net>
  *@copyright © 2001-2009 Will Entriken
  *@access public
  *@link http://fdcl.sourceforge.net
  */
  /**
  */
$db_host = 'localhost';
$db_name = 'fdcl';
$db_user = 'cameralifeuser';
$db_pass = 'password';
$db_prefix = '';
?>
