<?php
  /**
  *Requires the classes
  *<ul>
  *<li>view</li>
  *<li>search</li>
  *<li>album</li>
  *<li>photo</li>
  *<li>folder</li>
  *<li>topic</li>
  *<li>stats</li>
  *<li>audittrail</li>
  *</ul>
  *@author Will Entriken <cameralife@phor.net>
  *@copyright Copyright (c) 2001-2009 Will Entriken
  *@access public
  */
  /**
  */
  require_once dirname(__FILE__) .'/view.class.php';
  require_once dirname(__FILE__) .'/search.class.php';
  require_once dirname(__FILE__) .'/album.class.php';
  require_once dirname(__FILE__) .'/photo.class.php';
  require_once dirname(__FILE__) .'/folder.class.php';
  require_once dirname(__FILE__) .'/topic.class.php';
  require_once dirname(__FILE__) .'/stats.class.php';
  require_once dirname(__FILE__) .'/audittrail.class.php';
?>
