<?php
namespace CameraLife;
/**
 * Loads all core classes
 */
require_once dirname(__FILE__) . '/view.class.php';
require_once dirname(__FILE__) . '/search.class.php';
require_once dirname(__FILE__) . '/album.class.php';
require_once dirname(__FILE__) . '/photo.class.php';
require_once dirname(__FILE__) . '/folder.class.php';
require_once dirname(__FILE__) . '/topic.class.php';
require_once dirname(__FILE__) . '/stats.class.php';
require_once dirname(__FILE__) . '/audittrail.class.php';
require_once dirname(__FILE__) . '/database.php';
